name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " event name ${{ github.event_name }} "
      - run: echo "The name of your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/push
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
